### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by richardj** [richardj/nowplaying#4]
- [ ] Create playlist option through Spotify API https://github.com/eddiemoore/angular-spotify
- [ ] Get all the friends (max 50 per call right now)
- [ ] Make playlist shareable through social media
- [ ] Find a default state (random user? / something else?)
